import { GATE, STANDARD_PATHS } from '../../config/standard';

import type { FC } from 'react';

export const AboutPage: FC = () => {
  return (
    <main className="page">
      <h1 className="page-title">About</h1>
      <p className="page-lede">
        This project was generated by linteljs, which applies one lint, type, test and agent standard and keeps
        applying it.
      </p>

      <section className="section">
        <h2 className="section-title">The gate</h2>
        <ul className="rows">
          {GATE.map(({ command, runs }) => {
            return (
              <li key={command} className="row">
                <code className="key">{command}</code>
                <span className="value">{runs}</span>
              </li>
            );
          })}
        </ul>
        <p className="note">
          <code>pnpm check</code>
          {' '}
          runs the four in order, and is what CI runs.
        </p>
      </section>

      <section className="section">
        <h2 className="section-title">Where the standard lives</h2>
        <dl className="rows">
          {STANDARD_PATHS.map(({ path, holds }) => {
            return (
              <div key={path} className="row">
                <dt><code>{path}</code></dt>
                <dd>{holds}</dd>
              </div>
            );
          })}
        </dl>
      </section>

      <section className="section">
        <h2 className="section-title">Keeping it current</h2>
        <p className="note">
          <code>pnpm dlx @linteljs/create sync</code>
          {' '}
          re-applies the standard after an update. It rewrites the
          toolchain and never touches your source.
        </p>
      </section>
    </main>
  );
};
