import { AppHeader } from '../components/features/app-header/AppHeader';
import { NAME } from '../config/linteljs';
import { DataProvider } from '../lib/providers/DataProvider';
import { StoreProvider } from '../lib/providers/StoreProvider';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './globals.css';

interface RootLayoutProps {
  readonly children: ReactNode;
}

// The document's own metadata, which is where a Next project sets what other targets set in `index.html`.
export const metadata: Metadata = {
  title: NAME,
  description: `${NAME}, generated by linteljs`,
};

/*
 * The App Router owns the document, so this file is the `<html>` other targets keep in an `index.html`. A server
 * component: the two slots below are the client boundary, and everything under them inherits it.
 */
const RootLayout = ({ children }: RootLayoutProps): ReactNode => {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <DataProvider>
            <AppHeader name={NAME} />
            {children}
          </DataProvider>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
