import { AppHeader } from '../components/features/app-header/AppHeader';
import { NAME } from '../config/linteljs';
import { DataProvider } from '../lib/providers/data/DataProvider';
import { StoreProvider } from '../lib/providers/store/StoreProvider';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './globals.css';

interface RootLayoutProps {
  readonly children: ReactNode;
}

export const metadata: Metadata = {
  title: NAME,
  description: `${NAME}, generated by linteljs`,
};

// The two slots below are the client boundary, and everything under them inherits it.
const RootLayout = ({ children }: RootLayoutProps): ReactNode => {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <DataProvider>
            <AppHeader name={NAME} />
            {children}
          </DataProvider>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
