import {
  mkdtempSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  copilotPayload,
  geminiPayload,
  runHook,
} from '@mocks/runHook';
import {
  afterEach,
  beforeEach,
  describe,
  expect,
  it,
} from 'vitest';

const GENERATED = /^`routeTree\.gen\.ts` is generated, as its first line says/u;

let cwd = '';

const editPayload = (path: string): object => {
  const payload = {
    cwd,
    hook_event_name: 'PreToolUse',
    tool_name: 'Edit',
    tool_input: {
      file_path: path,
      old_string: 'a',
      new_string: 'b',
    },
  };

  return payload;
};

beforeEach(() => {
  const prefix = join(tmpdir(), 'linteljs-generated-hook-');
  cwd = mkdtempSync(prefix);
  writeFileSync(join(cwd, 'routeTree.gen.ts'), '// This file was automatically generated by TanStack Router.\n');
  writeFileSync(join(cwd, 'app.ts'), 'export {};\n');
});

afterEach(() => {
  rmSync(cwd, {
    force: true,
    recursive: true,
  });
});

describe('generatedFileGuardHook.ts', () => {
  it('denies an edit to a generated file, and clears one to a written one', () => {
    const generated = runHook('generatedFileGuardHook.ts', editPayload('routeTree.gen.ts'));
    const written = runHook('generatedFileGuardHook.ts', editPayload('app.ts'));

    expect(generated).toMatch(GENERATED);
    expect(written).toBeUndefined();
  });

  it('denies a Copilot edit to a generated file', () => {
    const reply = runHook('generatedFileGuardHook.ts', copilotPayload('edit', { path: 'routeTree.gen.ts' }, cwd));
    expect(reply).toMatch(GENERATED);
  });

  it.each(['write_file', 'replace'])('denies Gemini CLI\'s %s on a generated file', (tool) => {
    const payload = geminiPayload('BeforeTool', tool, { file_path: 'routeTree.gen.ts' }, cwd);
    const reply = runHook('generatedFileGuardHook.ts', payload);
    expect(reply).toMatch(GENERATED);
  });

  it('stays silent on malformed JSON and under Cursor, whose edit event names no file', () => {
    const malformed = runHook('generatedFileGuardHook.ts', '{');
    const cursor = runHook('generatedFileGuardHook.ts', {
      ...editPayload('routeTree.gen.ts'),
      cursor_version: '2.4.0',
    });

    expect(malformed).toBeUndefined();
    expect(cursor).toBeUndefined();
  });
});
