import {
  mkdtempSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  afterEach,
  beforeEach,
  describe,
  expect,
  it,
} from 'vitest';

import { generatedFileReason } from './generatedFileUtils.ts';

let cwd = '';

const reasonFor = (firstLine: string, rest = ''): string | undefined => {
  writeFileSync(join(cwd, 'file.ts'), `${firstLine}\n${rest}`);

  return generatedFileReason({
    host: 'claude',
    cwd,
    paths: ['file.ts'],
  });
};

beforeEach(() => {
  const prefix = join(tmpdir(), 'linteljs-generated-');
  cwd = mkdtempSync(prefix);
});

afterEach(() => {
  rmSync(cwd, {
    force: true,
    recursive: true,
  });
});

describe('generatedFileReason', () => {
  it.each([
    '// @generated by relay-compiler',
    '/* DO NOT EDIT. */',
    '# Auto-generated by openapi-generator',
    '// autogenerated file',
    '// This file was automatically generated by TanStack Router.',
    '// Code generated by protoc-gen-go. DO NOT EDIT.',
  ])('denies an edit to a file whose first line reads `%s`', (firstLine) => {
    const reason = reasonFor(firstLine);

    expect(reason).toBe(`\`file.ts\` is generated, as its first line says: \`${firstLine}\`. Change what it is `
      + 'generated from and run that generator again; an edit here is lost on its next run.');
  });

  it.each([
    [
      'a plain first line',
      '// The router.',
      '',
    ],
    [
      'a marker below the first line',
      'export {};',
      '// @generated',
    ],
    [
      'a word that only contains a marker',
      '// donot editorialize',
      '',
    ],
  ])('clears %s', (_label, firstLine, rest) => {
    const reason = reasonFor(firstLine, rest);
    expect(reason).toBeUndefined();
  });

  it('quotes a long first line cut short, and reads a CRLF file', () => {
    const reason = reasonFor(`// @generated ${'x'.repeat(200)}\r`);
    const quoted = `// @generated ${'x'.repeat(106)}`;

    expect(reason).toContain(`\`${quoted}\`.`);
  });

  it('clears a file that does not exist yet, and reads every path it is given', () => {
    writeFileSync(join(cwd, 'gen.ts'), '// @generated\n');
    const missing = generatedFileReason({
      host: 'claude',
      cwd,
      paths: ['new.ts'],
    });
    const second = generatedFileReason({
      host: 'copilot',
      cwd,
      paths: ['new.ts', join(cwd, 'gen.ts')],
    });

    expect(missing).toBeUndefined();
    expect(second).toMatch(/is generated, as its first line says: `\/\/ @generated`\./u);
  });
});
