import { For, type JSX } from 'solid-js';

import {
  CHECK,
  GATE,
  SYNC,
} from '@config/linteljs';
import { STANDARD_PATHS } from '@config/standard';

export const AboutPage = (): JSX.Element => {
  return (
    <main class="page">
      <h1 class="page-title">About</h1>
      <p class="page-lede">
        This project was generated by linteljs, which applies one lint, type, test and agent standard and keeps
        applying it.
      </p>

      <section class="section">
        <h2 class="section-title">The gate</h2>
        <ul class="rows">
          <For each={GATE}>
            {(leg) => {
              return (
                <li class="row">
                  <code class="key">{leg.command}</code>
                  <span class="value">{leg.runs}</span>
                </li>
              );
            }}
          </For>
        </ul>
        <p class="note">
          <code>{CHECK}</code>
          {' '}
          runs them in order, and is what CI runs.
        </p>
      </section>

      <section class="section">
        <h2 class="section-title">Where the standard lives</h2>
        <dl class="rows">
          <For each={STANDARD_PATHS}>
            {(entry) => {
              return (
                <div class="row">
                  <dt><code>{entry.path}</code></dt>
                  <dd>{entry.holds}</dd>
                </div>
              );
            }}
          </For>
        </dl>
      </section>

      <section class="section">
        <h2 class="section-title">Keeping it current</h2>
        <p class="note">
          <code>{SYNC}</code>
          {' '}
          re-applies the standard after an update. It rewrites the agent plugin, asks before it changes
          the ESLint config or package.json, and never touches your source.
        </p>
      </section>
    </main>
  );
};
