import {
  type Answers,
  type DefineConfigOptions,
  hasLibrary,
  LIBRARY_LAYERS,
} from '../../model/answers/answers';
import { targetFor } from '../../model/targets';
import { buildAliases } from '../build-aliases/buildAliases';

// Keyed by `keyof DefineConfigOptions`, so a renamed option fails to compile here rather than in a project.
type OptionRow = [keyof DefineConfigOptions, string];

// The subpath, not the barrel, which loads all six framework layers.
const PACKAGE = '@linteljs/eslint-config/define-config';

// Generated by `@tanstack/router-plugin` on every run, committed so `tsc` passes before the first.
export const ROUTE_TREE = 'src/routeTree.gen.ts';

// `plugins/linteljs/` is shipped, not written here; `.agents/` is the codex half of `.claude/`. Ignoring one and
// not the other made a real project's gate fail on skill files mirrored into `.agents/`.

const BASE_IGNORES = [
  'dist/**',
  'coverage/**',
  '.claude/**',
  '.agents/**',
  'plugins/linteljs/**',
];

// `String.raw` for a value carrying a backslash, which an ordinary literal parses back as an escape.
const quote = (value: string): string => {
  if (value.includes('\\')) {
    return `String.raw\`${value}\``;
  }

  return `'${value.replaceAll("'", "\\'")}'`;
};

const indentOf = (level: number): string => {
  return '  '.repeat(level);
};

// Matches the emitted @stylistic/max-len; looser, React Native's ignores self-reported a finding.
const MAX_LINE = 120;

const arrayLiteral = (key: string, values: string[], level = 1): string => {
  const inline = `[${values.map(quote).join(', ')}]`;

  if (`${indentOf(level)}${key}: ${inline},`.length <= MAX_LINE) {
    return inline;
  }

  const entries = values.map((value) => {
    return `${indentOf(level + 1)}${quote(value)},`;
  });

  return `[\n${entries.join('\n')}\n${indentOf(level)}]`;
};

const objectLiteral = (entries: [string, string][], level: number): string => {
  const inner = entries
    .map(([key, value]) => {
      return `${indentOf(level + 1)}${quote(key)}: ${quote(value)},`;
    })
    .join('\n');

  return `{\n${inner}\n${indentOf(level)}}`;
};

// Layer switches first, then what `base` reads.
const optionRows = (answers: Answers): OptionRow[] => {
  const target = targetFor(answers);
  const rows: OptionRow[] = [];

  if (target.framework !== undefined) {
    rows.push(['framework', quote(target.framework)]);
  }

  // Unconditional: this CLI generates TypeScript only.
  rows.push(['typescript', 'true']);

  // Follows the suite: the layer imports @vitest/eslint-plugin, which dies on ERR_MODULE_NOT_FOUND without one.
  if (answers.testing === 'vitest') {
    rows.push(['vitest', 'true']);
  }

  if (target.html) {
    rows.push(['html', 'true']);
  }

  // A file type, so it stacks with the hosted framework.
  if (target.astro === true) {
    rows.push(['astro', 'true']);
  }

  const layers = LIBRARY_LAYERS.filter((layer) => {
    return layer === 'tanstack-router' ? answers.router === 'tanstack-router' : hasLibrary(answers, layer);
  });

  if (layers.length > 0) {
    rows.push(['libraries', arrayLiteral('libraries', layers)]);
  }

  // Without the entry point `better-tailwindcss` warns once per class string: 63 warnings on one real project.
  const { styleEntry } = target;

  if (hasLibrary(answers, 'tailwind') && styleEntry !== undefined) {
    rows.push(['tailwindEntryPoint', quote(`./${styleEntry}`)]);
  }

  // Only where recorded; `@linteljs/eslint-config` explains why the order is not a safe default.
  const { resolveConditions } = answers;

  if (resolveConditions !== undefined) {
    rows.push(['resolver', `{ conditionNames: ${arrayLiteral('conditionNames', resolveConditions, 2)} }`]);
  }

  // The project's own last. Only what `.gitignore` cannot name belongs here: a generated file a project commits.
  rows.push([
    'ignores',
    arrayLiteral('ignores', [
      ...BASE_IGNORES,
      ...target.ignores,
      ...(answers.router === 'tanstack-router' ? [ROUTE_TREE] : []),
      ...answers.ignores ?? [],
    ]),
  ]);
  rows.push(['aliases', objectLiteral(Object.entries(buildAliases(answers)), 1)]);
  rows.push(['naming', objectLiteral(Object.entries(target.naming), 1)]);
  rows.push(['folderNaming', objectLiteral(Object.entries(target.folderNaming), 1)]);

  return rows;
};

export const emitEslintConfig = (answers: Answers): string => {
  const options = optionRows(answers)
    .map(([key, value]) => {
      return `${indentOf(1)}${key}: ${value},`;
    })
    .join('\n');

  // Named: import/no-anonymous-default-export reports a bare array.
  return [
    `import { defineConfig } from '${PACKAGE}';`,
    '',
    `const config = await defineConfig({\n${options}\n});`,
    '',
    'export default config;',
    '',
  ].join('\n');
};
