import {
  type Answers,
  type DefineConfigOptions,
  hasLibrary,
  LIBRARY_LAYERS,
} from '../../model/answers/answers';
import { targetFor } from '../../model/targets';
import { buildAliases } from '../build-aliases/buildAliases';

// Keyed by `keyof DefineConfigOptions`: a renamed or invented option fails to compile here, not in a project.
type OptionRow = [keyof DefineConfigOptions, string];

// The subpath, not the barrel: the barrel loads all six framework layers, five unneeded by any one project.
const PACKAGE = '@linteljs/eslint-config/define-config';

/**
 * Applied everywhere; per-target additions come from the target record. `plugins/linteljs/` is shipped, not written
 * here, so linting it gates a project on a file it does not own and cannot fix without a release.
 * `.agents/` is the codex half of `.claude/` and is ignored on the same grounds: this CLI writes
 * `.agents/plugins/marketplace.json` itself, and an agent host's own directory is not project source. Ignoring one
 * and not the other made a real project's gate fail on skill files mirrored into `.agents/`.
 */
// Generated by `@tanstack/router-plugin` on every dev and build run, and committed so `tsc` passes before the first.
export const ROUTE_TREE = 'src/routeTree.gen.ts';

const BASE_IGNORES = [
  'dist/**',
  'coverage/**',
  '.claude/**',
  '.agents/**',
  'plugins/linteljs/**',
];

/**
 * A backslash cannot be written straight through: in an ordinary string literal it parses back as an escape, so the
 * emitted pattern is not the one intended. `String.raw` says that once, where doubling every backslash says it per
 * character and leaves the reader counting them. Only a value that actually carries one takes the tag; everything else
 * stays a plain quoted string.
 */
const quote = (value: string): string => {
  if (value.includes('\\')) {
    return `String.raw\`${value}\``;
  }

  return `'${value.replaceAll("'", "\\'")}'`;
};

const indentOf = (level: number): string => {
  return '  '.repeat(level);
};

// Matches @stylistic/max-len (120); a looser value let React Native's ignores self-report a lint finding.
const MAX_LINE = 120;

const arrayLiteral = (key: string, values: string[], level = 1): string => {
  const inline = `[${values.map(quote).join(', ')}]`;

  // The whole emitted line, key and trailing comma included, which is what max-len measures.
  if (`${indentOf(level)}${key}: ${inline},`.length <= MAX_LINE) {
    return inline;
  }

  const entries = values.map((value) => {
    return `${indentOf(level + 1)}${quote(value)},`;
  });

  return `[\n${entries.join('\n')}\n${indentOf(level)}]`;
};

const objectLiteral = (entries: [string, string][], level: number): string => {
  const inner = entries
    .map(([key, value]) => {
      return `${indentOf(level + 1)}${quote(key)}: ${quote(value)},`;
    })
    .join('\n');

  return `{\n${inner}\n${indentOf(level)}}`;
};

// The layer switches lead, then the options `base` reads, so "which layers" is answered at the top of the object.
const optionRows = (answers: Answers): OptionRow[] => {
  const target = targetFor(answers);
  const rows: OptionRow[] = [];

  if (target.framework !== undefined) {
    rows.push(['framework', quote(target.framework)]);
  }

  // Unconditional: this CLI generates TypeScript only; the option stays in `defineConfig` for a hand-written config.
  rows.push(['typescript', 'true']);

  // Follows the suite, not the target: it imports @vitest/eslint-plugin, so asking for it without one dies on
  // ERR_MODULE_NOT_FOUND before eslint . lints a line.
  if (answers.testing === 'vitest') {
    rows.push(['vitest', 'true']);
  }

  if (target.html) {
    rows.push(['html', 'true']);
  }

  // A file type, so it stacks with whatever framework the site hosts rather than standing in for one.
  if (target.astro === true) {
    rows.push(['astro', 'true']);
  }

  const layers = LIBRARY_LAYERS.filter((layer) => {
    return layer === 'tanstack-router' ? answers.router === 'tanstack-router' : hasLibrary(answers, layer);
  });

  if (layers.length > 0) {
    rows.push(['libraries', arrayLiteral('libraries', layers)]);
  }

  /**
   * Names the stylesheet the theme lives in, so `better-tailwindcss` reasons about the project's own tokens rather
   * than Tailwind's defaults. Without it the plugin warns once per class string that the entry point is `undefined`
   * and orders custom tokens as unknowns: 63 warnings on one real project. Only where the target has a stylesheet to
   * name, which is every one but Svelte.
   */
  const { styleEntry } = target;

  if (hasLibrary(answers, 'tailwind') && styleEntry !== undefined) {
    rows.push(['tailwindEntryPoint', quote(`./${styleEntry}`)]);
  }

  /**
   * Only where the project recorded them. A dependency publishing subpaths through a wildcard `exports` map that the
   * `types` condition cannot satisfy is the case this exists for; `@linteljs/eslint-config` explains why the order is
   * not a safe default.
   */
  const { resolveConditions } = answers;

  if (resolveConditions !== undefined) {
    rows.push(['resolver', `{ conditionNames: ${arrayLiteral('conditionNames', resolveConditions, 2)} }`]);
  }

  // The project's own last, after the shared list and the target's. `base()` already ignores whatever `.gitignore`
  // does, so what belongs here is only what that file cannot name: a generated file a project commits.
  rows.push([
    'ignores',
    arrayLiteral('ignores', [
      ...BASE_IGNORES,
      ...target.ignores,
      ...(answers.router === 'tanstack-router' ? [ROUTE_TREE] : []),
      ...answers.ignores ?? [],
    ]),
  ]);
  rows.push(['aliases', objectLiteral(Object.entries(buildAliases(answers)), 1)]);
  rows.push(['naming', objectLiteral(Object.entries(target.naming), 1)]);
  rows.push(['folderNaming', objectLiteral(Object.entries(target.folderNaming), 1)]);

  return rows;
};

export const emitEslintConfig = (answers: Answers): string => {
  const options = optionRows(answers)
    .map(([key, value]) => {
      return `${indentOf(1)}${key}: ${value},`;
    })
    .join('\n');

  // Named, not anonymous (like lint-staged.config.js): import/no-anonymous-default-export reports a bare array.
  return [
    `import { defineConfig } from '${PACKAGE}';`,
    '',
    `const config = await defineConfig({\n${options}\n});`,
    '',
    'export default config;',
    '',
  ].join('\n');
};
