import {
  CHECK,
  GATE,
  SYNC,
} from '@config/linteljs';
import { STANDARD_PATHS } from '@config/standard';

import type { ReactNode } from 'react';

const AboutPage = (): ReactNode => {
  return (
    <main className="page">
      <h1 className="page-title">About</h1>
      <p className="page-lede">
        This project was generated by linteljs, which applies one lint, type, test and agent standard and keeps
        applying it.
      </p>

      <section className="section">
        <h2 className="section-title">The gate</h2>
        <ul className="rows">
          {GATE
            .map(({ command, runs }) => {
              return (
                <li key={command} className="row">
                  <code className="key">{command}</code>
                  <span className="value">{runs}</span>
                </li>
              );
            })}
        </ul>
        <p className="note">
          <code>{CHECK}</code>
          {' '}
          runs them in order, and is what CI runs.
        </p>
      </section>

      <section className="section">
        <h2 className="section-title">Where the standard lives</h2>
        <dl className="rows">
          {STANDARD_PATHS
            .map(({ path, holds }) => {
              return (
                <div key={path} className="row">
                  <dt><code>{path}</code></dt>
                  <dd>{holds}</dd>
                </div>
              );
            })}
        </dl>
      </section>

      <section className="section">
        <h2 className="section-title">Keeping it current</h2>
        <p className="note">
          <code>{SYNC}</code>
          {' '}
          re-applies the standard after an update. It rewrites the
          agent plugin, asks before it changes
          the ESLint config or package.json, and never touches your source.
        </p>
      </section>
    </main>
  );
};

export default AboutPage;
