<script lang="ts">
  import { GATE, STANDARD_PATHS } from '../../config/standard';
</script>

<main class="page">
  <h1 class="page-title">About</h1>
  <p class="page-lede">
    This project was generated by linteljs, which applies one lint, type, test and agent standard
    and keeps applying it.
  </p>

  <section class="section">
    <h2 class="section-title">The gate</h2>
    <ul class="rows">
      {#each GATE as leg (leg.command)}
        <li class="row">
          <code class="key">{leg.command}</code>
          <span class="value">{leg.runs}</span>
        </li>
      {/each}
    </ul>
    <p class="note">
      <code>pnpm check</code> runs the four in order, and is what CI runs.
    </p>
  </section>

  <section class="section">
    <h2 class="section-title">Where the standard lives</h2>
    <dl class="rows">
      {#each STANDARD_PATHS as entry (entry.path)}
        <div class="row">
          <dt><code>{entry.path}</code></dt>
          <dd>{entry.holds}</dd>
        </div>
      {/each}
    </dl>
  </section>

  <section class="section">
    <h2 class="section-title">Keeping it current</h2>
    <p class="note">
      <code>pnpm dlx @linteljs/create sync</code> re-applies the standard after an update. It
      rewrites the toolchain and never touches your source.
    </p>
  </section>
</main>
