<script setup lang="ts">
import { CHECK, GATE } from '@config/linteljs';
import { STANDARD_PATHS } from '@config/standard';
</script>

<template>
  <main class="page">
    <h1 class="page-title">
      About
    </h1>
    <p class="page-lede">
      This project was generated by linteljs, which applies one lint, type, test and agent standard
      and keeps applying it.
    </p>

    <section class="section">
      <h2 class="section-title">
        The gate
      </h2>
      <ul class="rows">
        <li
          v-for="leg in GATE"
          :key="leg.command"
          class="row"
        >
          <code class="key">{{ leg.command }}</code>
          <span class="value">{{ leg.runs }}</span>
        </li>
      </ul>
      <p class="note">
        <code>{{ CHECK }}</code> runs them in order, and is what CI runs.
      </p>
    </section>

    <section class="section">
      <h2 class="section-title">
        Where the standard lives
      </h2>
      <dl class="rows">
        <div
          v-for="entry in STANDARD_PATHS"
          :key="entry.path"
          class="row"
        >
          <dt><code>{{ entry.path }}</code></dt>
          <dd>{{ entry.holds }}</dd>
        </div>
      </dl>
    </section>

    <section class="section">
      <h2 class="section-title">
        Keeping it current
      </h2>
      <p class="note">
        <code>npx @linteljs/create sync</code> re-applies the standard after an update. It
        rewrites the toolchain and never touches your source.
      </p>
    </section>
  </main>
</template>
