import { NAME } from '@config/linteljs';

import { DataProvider } from '@lib/providers/data/DataProvider';
import { I18nProvider } from '@lib/providers/i18n/I18nProvider';
import { StoreProvider } from '@lib/providers/store/StoreProvider';

import { AppHeader } from '@features/app-header/AppHeader';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './globals.css';

interface RootLayoutProps {
  readonly children: ReactNode;
}

export const metadata: Metadata = {
  title: NAME,
  description: `${NAME}, generated by linteljs`,
};

// The server renders English, and `I18nProvider` switches to the reader's language once hydrated.
// The three slots below are the client boundary, and everything under them inherits it.
const RootLayout = ({ children }: RootLayoutProps): ReactNode => {
  return (
    <html lang="en" dir="ltr">
      <body>
        <I18nProvider>
          <StoreProvider>
            <DataProvider>
              <AppHeader name={NAME} />
              {children}
            </DataProvider>
          </StoreProvider>
        </I18nProvider>
      </body>
    </html>
  );
};

export default RootLayout;
