import { headers } from 'next/headers';

import { NAME } from '@config/linteljs';

import { DataProvider } from '@lib/providers/data/DataProvider';
import { I18nProvider } from '@lib/providers/i18n/I18nProvider';
import { StoreProvider } from '@lib/providers/store/StoreProvider';
import { detectLanguage, directionOf } from '@i18n';
import { acceptedTags } from '@i18n/utils/cookieUtils';

import { AppHeader } from '@features/app-header/AppHeader';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import './globals.css';

interface RootLayoutProps {
  readonly children: ReactNode;
}

export const metadata: Metadata = {
  title: NAME,
  description: `${NAME}, generated by linteljs`,
};

// The server renders the reader's language from the request, so the first byte is already in it.
// The three providers below are the client boundary, and everything under them inherits it.
const RootLayout = async ({ children }: RootLayoutProps): Promise<ReactNode> => {
  const request = await headers();
  const cookies = request.get('cookie') ?? '';
  const preferred = acceptedTags(request.get('accept-language') ?? '');
  const language = detectLanguage(cookies, preferred);

  return (
    <html lang={language} dir={directionOf(language)}>
      <body>
        <I18nProvider language={language}>
          <StoreProvider>
            <DataProvider>
              <AppHeader name={NAME} />
              {children}
            </DataProvider>
          </StoreProvider>
        </I18nProvider>
      </body>
    </html>
  );
};

export default RootLayout;
